# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the sphinx/ directory with Sphinx
sphinx:
  builder: html
  configuration: sphinx/conf.py

# Build sphinx in additional formats such as PDF and ePub
formats:
  - pdf

# Set the version of Python and install method
python:
  version: 3.6
  install:
    - method: setuptools
      path: .